### ISSUE TITLE
你好，在华为荣耀play上能显示消息，但是启动应用后消息提示并不能消失，实测小米ok。

### ISSUE THREAD

**Issue by Pgrammerybj** [GiveSmile/BadgeForAppIcon-master#1]
如题，能不能暴露一个移除消息的方法呢，或者需要我们自己再次发送数量为0的消息？

**Comment by ybzqh** [comment]
是这个demo  不能取消么   我又暴露一个初始化的方法给你们调用初始化的
![图片](https://user-images.githubusercontent.com/45993544/56340323-2e601f80-61e4-11e9-8076-0b91650b9470.png)

**Comment by ybzqh** [comment]
你用直接导入demo里面的badges那个model用吧

**Comment by Pgrammerybj** [comment]
哈哈，在应用初始化的时候给他置为了0，也能解决问题，关于这个角标的问题想具体问问你方便微信不？

IPhone 7 Plus 版 Outlook<https://aka.ms/qtex0l>
________________________________
发件人: GiveSmile <notifications@github.com>
发送时间: Thursday, April 18, 2019 2:13:54 PM
收件人: GiveSmile/BadgeForAppIcon-master
抄送: 杨保疆; Author
主题: Re: [GiveSmile/BadgeForAppIcon-master] 你好，在华为荣耀play上能显示消息，但是启动应用后消息提示并不能消失，实测小米ok。 (#1)


是这个demo 不能取消么 我又暴露一个初始化的方法给你们调用初始化的
[图片]<https://user-images.githubusercontent.com/45993544/56340323-2e601f80-61e4-11e9-8076-0b91650b9470.png>

―

**Comment by GiveSmile** [comment]
z13657342680

**Comment by GiveSmile** [comment]
z13657342680
